Lint/DuplicateMethods:
  Enabled: true

Lint/UnusedMethodArgument:
  Enabled: true


Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

# Offense count: 13
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes.
# URISchemes: http, https
Metrics/LineLength:
  Max: 80

Metrics/MethodLength:
  Enabled: false

# Offense count: 1
Metrics/PerceivedComplexity:
  Max: 8


Performance/RedundantBlockCall:
  Enabled: true


Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/ClassVars:
  Enabled: true

Style/DeprecatedHashMethods:
  Enabled: true

Style/Documentation:
  Enabled: true

Style/DoubleNegation:
  Enabled: true

Style/EmptyLineBetweenDefs:
  Enabled: true

Style/EmptyLiteral:
  Enabled: true

Style/GuardClause:
  Enabled: true

Style/HashSyntax:
  Enabled: true

Style/MethodName:
  Enabled: true

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/NumericLiterals:
  MinDigits: 5

Style/OpMethod:
  Enabled: true

Style/RedundantReturn:
  Enabled: true

Style/RedundantSelf:
  Enabled: true

Style/SingleLineMethods:
  Enabled: false

Style/SpaceAfterComma:
  Enabled: true

Style/SpaceAroundEqualsInParameterDefault:
  Enabled: true

Style/SpaceAroundOperators:
  Enabled: true

Style/SpaceBeforeSemicolon:
  Enabled: true

Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names

Style/StringLiterals:
  Enabled: true

Style/TrivialAccessors:
  Enabled: true

Style/UnneededPercentQ:
  Enabled: true
