inherit_from: .rubocop_todo.yml

Metrics/ClassLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation
