inherit_from: .rubocop_todo.yml

Metrics/AbcSize:
  Enabled: false

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Metrics/ClassLength:
  Enabled: false

Style/Documentation:
  Enabled: true

Metrics/MethodLength:
  Enabled: false

