inherit_from: .rubocop_todo.yml

Lint/DuplicateMethods:
  Enabled: true

Lint/UnusedMethodArgument:
  Enabled: true


Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false


Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/Documentation:
  Enabled: true
